### ISSUE TITLE
Generate json files

### ISSUE THREAD

**Issue by megapctr** [webpack-contrib/i18n-webpack-plugin#11]
Is there an easy way to generate json files for each language? Incremental generation would be awesome (i.e. it won't remove existing translations.)

**Comment by megapctr** [comment]
I managed to get what I needed with the help of [i18n-extract](https://github.com/oliviertassinari/i18n-extract) module

**Comment by ezmiller** [comment]
anyone know if there's a way to do this with pybabel?

**Comment by miamollie** [comment]
Hey @megapctr, any chance you could share your `i18n-extract` solution for extracting strings into json? Thanks!

**Comment by ffigiel** [comment]
I haven't touched it in a looong while, but you can see it here. It's a node script. https://github.com/s3v3ns/sxconsole/blob/master/i18n-manager.js

**Comment by miamollie** [comment]
@megapctr Thanks for sharing, really helps!
