### ISSUE TITLE
Can't find variable: __, when run Unit Test scripts

### ISSUE THREAD

**Issue by shuson** [webpack-contrib/i18n-webpack-plugin#19]
Hi, I applied i18n plugin of webpack to my code, which will wrap String variables as __("Hello World"), the problem occurs when run Unit Test/

It says __ cannot be found.

Any idea? To mock it or load from somewhere else

**Comment by trashgenerator** [comment]
I have such mock in my `test_helpers.js`:
```
global.__ = str => str;
```

**Comment by EcutDavid** [comment]
@shuson as @nosovsh mentioned, we have to add the shim by ourselves if you are not using webpack and same webpack configuration 😃
