### ISSUE TITLE
Hide warnings about missing localizations

### ISSUE THREAD

**Issue by nosovsh** [webpack-contrib/i18n-webpack-plugin#20]
Is it possible to not show warnings about missing translations that are appearing in the console when webpack is building a project?

```
    WARNING in ./src/someFile.js
    Missing localization: [Paused]
    Missing localization: [Unpaused]
```

Or maybe it is possible to do it on webpack level not on this plugin level?

**Comment by EcutDavid** [comment]
@nosovsh, now you can use the `hideMessage` option for your goal: https://github.com/webpack/i18n-webpack-plugin#options
Thanks to @zhaoshengjun for the PR.
