### ISSUE TITLE
drop the use of deprecated feature of webpack

### ISSUE THREAD

**Issue by e-cloud** [webpack-contrib/i18n-webpack-plugin#22]
As the [source of webpack compiler](https://github.com/webpack/webpack/blob/master/lib/Compiler.js#L167) says, should use the (new) interface.

**Comment by EcutDavid** [comment]
Thanks, @e-cloud.
Would you like to send the PR?

**Comment by e-cloud** [comment]
sorry, i have no time for other project for now :weary: . Just report it

**Comment by BrainCrumbz** [comment]
this is the actual output coming out from running webpack tests:

```
  .....................................................................................
  .....................................................................................
  .........................................................................webpack: Using compiler.parser is deprecated.
Use compiler.plugin("compilation", function(compilation, data) {
  data.normalModuleFactory.plugin("parser", function(parser, options) { parser.plugin(/* ... */); });
}); instead. It was called at I18nPlugin.apply (D:\WS\JS\webpack\node_modules\i18n-webpack-plugin\index.js:43:18).
webpack: Using compiler.parser is deprecated.
Use compiler.plugin("compilation", function(compilation, data) {
  data.normalModuleFactory.plugin("parser", function(parser, options) { parser.plugin(/* ... */); });
}); instead. It was called at I18nPlugin.apply (D:\WS\JS\webpack\node_modules\i18n-webpack-plugin\index.js:43:18).


............
  .....................................................................................
```

**Comment by EcutDavid** [comment]
Fixed now.
@BrainCrumbz thanks for tour work, but merged @vivek12345 's work since I'm not sure why your PR didn't passed the CI.

**Comment by BrainCrumbz** [comment]
Well, that was 5 months ago, I don't know either! ;)

**Comment by alphapilgrim** [comment]
@EcutDavid  not sure I understand the solution for this. how can I get rid of the error displaying in the terminal? I have the latest, please help.
`webpack: Using compiler.parser is deprecated.
Use compiler.plugin("compilation", function(compilation, data) {
  data.normalModuleFactory.plugin("parser", function(parser, options) { parser.plugin(/* ... */); });
}); instead. It was called at I18nPlugin.apply (/node_modules/i18n-webpack-plugin/index.js:43:18).
Error: not a directory
    at MemoryFileSystem.mkdirpSync (/node_modules/memory-fs/lib/MemoryFileSystem.js:144:10)
    at MemoryFileSystem.(anonymous function) [as mkdirp] (/node_modules/memory-fs/lib/MemoryFileSystem.js:279:34)
    at Compiler.<anonymous> (/node_modules/webpack/lib/Compiler.js:322:27)
    at /node_modules/async/dist/async.js:3025:16
    at eachOfArrayLike (/node_modules/async/dist/async.js:940:9)
    at eachOf (/node_modules/async/dist/async.js:990:5)
    at Object.eachLimit (/node_modules/async/dist/async.js:3089:3)
    at Compiler.emitFiles (/node_modules/webpack/lib/Compiler.js:312:20)
    at Immediate._onImmediate (/node_modules/memory-fs/lib/MemoryFileSystem.js:288:4)
    at tryOnImmediate (timers.js:534:15)
    at processImmediate [as _immediateCallback] (timers.js:514:5)`
