### ISSUE TITLE
ReferenceError: __ is not defined

### ISSUE THREAD

**Issue by rafaelmaruta** [webpack-contrib/i18n-webpack-plugin#30]
I updated to webpack 2.2 stable version yesteday and later I npm installed the i18n-webpack-plugin, but it threw the warning "compile.parser is deprecated" in node, so I cloned the plugin from repository which apparently has the correction. After putting a "(" char in the line 86 because of an error, it now throws the error in the browser:

ReferenceError: __ is not defined

**Comment by rafaelmaruta** [comment]
@sokra can u help me plz?

**Comment by josemigg** [comment]
did you fix it? I'm having the same issue

**Comment by rafaelmaruta** [comment]
No, I don't

**Comment by evilebottnawi** [comment]
@rafaelmaruta can you create minimal reproducible test repo?

**Comment by SimonVanneste** [comment]
Are you using eslint as a preloader? I fixed a similar error by adding `__` as a global in eslintconfig

**Comment by evilebottnawi** [comment]
@rafaelmaruta @josemigg friendly ping. Can your create minimal reproducible test repo?

**Comment by rafaelmaruta** [comment]
Sorry, I didn't receive the message. Only the npm version was broken, the github version was working fine.
