### ISSUE TITLE
Nested support problem

### ISSUE THREAD

**Issue by tanagumo** [webpack-contrib/i18n-webpack-plugin#33]
I want to use nested support option, but I don't have any good idea to hundle a case like below.

```
"foo": {"bar": "バー", "baz": "バズ"},
"Webpack is awesome. It's a great tool!!": "Webpackは素晴らしいツールです!"
```

Since nested option splits keys by dot,  `__('Webpack is awesome. It's a great tool!!')` does not translate correctly.

Is there any good idea?

**Comment by sullenor** [comment]
Looks like it will be better to move the path to the another argument, so it would look like:

`__('foo', 'bar')`
