### ISSUE TITLE
inline html (br, strong, em)

### ISSUE THREAD

**Issue by sidonaldson** [webpack-contrib/i18n-webpack-plugin#37]
Is there a way to include html elements such as strong, br, em etc?

I've tried adding them as text and also entities but they still show as text content.

Any help is really appreciated :)

**Comment by EcutDavid** [comment]
Hi @sidonaldson, it's not related to this plugin. 
This plugin only handle the text transform part, we need consider how to transform these text in DOM by ourselves.

**Comment by sidonaldson** [comment]
Thanks @EcutDavid 

You're right. In my specific case I couldn't get the inline html to show in a handlebars template and I've since learnt that you need to using their HTML escaping syntax of triple curly braces!

```
<h1>{{{htmlWebpackPlugin.options.data.title}}}</h1>
```
and with React you would need to use `dangerouslySetInnerHTML` etc.

Hope this helps others.
